###
POST http://localhost:9000/api/newUser HTTP/1.1
Content-Type: application/json


{
    "nombre":"Jorge",
    "edad":22,
    "username":"JorgeGs",
    "password":"jyojis"
}

###
GET http://localhost:9000/api/newUser HTTP/1.1

###
GET http://localhost:9000/api/newUser/631eec63ae143ada8449ae48 HTTP/1.1

###
PUT  http://localhost:9000/api/newUser/631eec63ae143ada8449ae48 HTTP/1.1
Content-Type: application/json


{
    "nombre":"Pablo",
    "edad":20,
    "username":"PabloGS",
    "password":"HumbertoGS"
}

###
DELETE  http://localhost:9000/api/newUser/631eec63ae143ada8449ae48 HTTP/1.1

